version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.2
    environment:
      TEST_REPORTS: /tmp/test-reports
    steps:
      - checkout
      - run:
          name: Activate venv and install requirements
          command: |
            python3 -m venv ~/venv
            echo ". ~/venv/bin/activate" >> $BASH_ENV
            source $BASH_ENV
      - run: make dependencies
      - run: make test

      - store_test_results:
          path: /tmp/test-reports

      - store_artifacts:
          path: /tmp/test-reports
workflows:
  version: 2
  test:
    jobs:
      - test
